### ISSUE TITLE
Simulator input files missing

### ISSUE THREAD

**Issue by bcampbell-ts** [mtconnect/mtconnect-agent#45]
Commit 45bc869876a312b42677b7594951c0581c894a0c updated the simulator files, but neglected to include the new input files.
Missing are:
`./adapters/simulator2/public/Mazak03.log`
`./adapters/simulator/public/Mazak01.log`

**Comment by wsobel** [comment]
Added logs. Please pull latest. Thx - W

**Comment by bcampbell-ts** [comment]
Thanks.
