### ISSUE TITLE
Processing of SSDP search responses is malformed

### ISSUE THREAD

**Issue by bcampbell-ts** [mtconnect/mtconnect-agent#47]
1. A response to M-SEARCH will always have a USN component.  The USN component will always start with the text `uuid:` (per UPnP Device Architecture 1.0 Document Revision Date 15 October 2008). The `parseHeaders` function improperly does not account for the leading `uuid:`

2. A response to M-SEARCH also has a LOCATION component which `contains a URL to the UPnP description of the root device.` The `parseHeaders` function does not allow the URL to contain the protocol, as it should. It is only looking for `ip:port` and will not function correctly if given `http://ip:port`

**Comment by wsobel** [comment]
1. I think I see the problem with the function regarding the split of the USN to remove the leading uuid.

2. I'll add http:// to be start of the LOCATION.

**Comment by wsobel** [comment]
This has now been addressed in Commit: cb1bc4904

**Comment by bcampbell-ts** [comment]
Now accepts correctly formed responses.
