### ISSUE TITLE
Data Item type names with more than 1 underscore are truncated

### ISSUE THREAD

**Issue by bcampbell-ts** [mtconnect/mtconnect-agent#48]
For example:
From Devices.xml
```xml
<DataItem category="SAMPLE" id="z_pulse_code_temperature" name="z_pulse_code_temperature" type="x:Z_PULSE_CODE_TEMPERATURE" />
```
View in agent /probe
```xml
<dataItem category="SAMPLE" id="MJo2ow0SP5" name="z_pulse_code_temperature" type="x:Z_PULSE_CODE_TEMPERATURE"/>
```

View in agent /current or /sample
```xml
 <ZPulse dataItemId="MJo2ow0SP5" timestamp="2017-11-08T14:30:42.755Z" sequence="801" name="z_pulse_code_temperature">32</ZPulse>
```

`x:Z_PULSE_CODE_TEMPERATURE` became `ZPulse` instead of expected `ZPulseCodeTemperature`

The problem is in pascalCase function which is hard coded to handle a single underscore.
I'll submit a PR to fix.

**Comment by wsobel** [comment]
Thanks a lot for helping out! I'm refactoring a lot of the code to clean up the idioms around discovery and data ingres. Any help is greatly appreciated. 

This should be an easy fix. 

Best 
W

(Sent from mobile)
