### ISSUE TITLE
License.txt

### ISSUE THREAD

**Issue by russwaddell** [mtconnect/mtconnect-agent#52]
Verify license is appropriate. C++ Agent is licensed under Apache; is there a standard license for Node.js whether it is Apache or something else? I don’t think MTConnect Implementer license was intended for this use.

**Comment by intolerance** [comment]
I could ask some of our legal staff to review if this is still an issue. Please let me know

**Comment by russwaddell** [comment]
Removed MTConnect Implementer License; added Apache license to README.md
